### ISSUE TITLE
Error al instalar librería

### ISSUE THREAD

**Issue by febefeebs** [Antoniogodoy17/SentimentAnalysis#7]
Hola!!
¿Qué versión de R se utiliza para correr el algoritmo? Estoy tratando de probar con R 3.6.1 y cuando trato de instalar la librería TextTools, me aparece el mensaje de "package ‘RTextTools’ is not available (for R version 3.6.1)"
¿Qué puedo hacer? ¿Es necesario utilizar otra versión de R?

**Comment by antoniogodoy17** [comment]
Qué tal.

Te marca error porque fue removido del repositorio activo de CRAN, como aparece en este enlace:

https://cran.r-project.org/web/packages/RTextTools/index.html

Ahí mismo aparece el enlace a la librería archivado. 

Tomaré como cerrado este issue.

**Comment by febefeebs** [comment]
Disculpa, cómo sé cuál escoger? Trato de instalar RTextTools 1.4.2 y me aparece un error que dice ERROR: dependencies 'SparseM', 'randomForest', 'tree', 'e1071', 'ipred', 'caTools', 'maxent', 'glmnet', 'tau' are not available for package 'RTextTools'...
¿Sabes por qué?
