### ISSUE TITLE
Instalación RTextTools

### ISSUE THREAD

**Issue by febefeebs** [Antoniogodoy17/SentimentAnalysis#8]
Qué tal.

Te marca error porque fue removido del repositorio activo de CRAN, como aparece en este enlace:

https://cran.r-project.org/web/packages/RTextTools/index.html

Ahí mismo aparece el enlace a la librería archivado. 

Tomaré como cerrado este issue.

_Originally posted by @antoniogodoy17 in https://github.com/antoniogodoy17/sentimentAnalysis/issues/7#issuecomment-542907019_
---------------------------------------------------------------------------------------------
Disculpa, cómo sé cuál escoger? Trato de instalar RTextTools 1.4.2 y me aparece un error que dice ERROR: dependencies 'SparseM', 'randomForest', 'tree', 'e1071', 'ipred', 'caTools', 'maxent', 'glmnet', 'tau' are not available for package 'RTextTools'...

¿Sabes por qué se genera ese error?

**Comment by antoniogodoy17** [comment]
Puedes escoger cualquiera que sea compatible con tu versión de R. Puedes buscar eso en las especificaciones del paquete, como aquí: https://www.rdocumentation.org/packages/RTextTools/versions/1.4.2

Y ese error te aparece porque RTextTools depende de otras librerías para funcionar (dependencias), que son las que te lista, y como no están instaladas, no puede funcionar. Debes instalarlas antes de continuar.
